'use client';
import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/AppShell';
import PageHeader from '../../components/PageHeader';
import SectionCard from '../../components/SectionCard';
import StatusBadge from '../../components/StatusBadge';
import EmptyState from '../../components/EmptyState';
import ErrorMessage from '../../components/ErrorMessage';
import FormField from '../../components/FormField';
import UserSelector from '../../components/UserSelector';
import { formatCurrency } from '../../lib/format';
import { bulkUpdateTransactionCategory, Category, deleteTransaction, getSystemCategories, getTransactions, getUserCategories, Transaction } from '../../lib/api';
const initialFilters = { from:'',to:'',merchant:'',transactionType:'',direction:'',minAmount:'',maxAmount:'' };
export default function TransactionsPage(){const [userId,setUserId]=useState('');const [rows,setRows]=useState<Transaction[]>([]);const [page,setPage]=useState(0);const [size,setSize]=useState('50');const [totalPages,setTotalPages]=useState(0);const [error,setError]=useState('');const [filters,setFilters]=useState(initialFilters);const [systemCategories,setSystemCategories]=useState<Category[]>([]);const [userCategories,setUserCategories]=useState<Category[]>([]);const [selectedIds,setSelectedIds]=useState<string[]>([]);const [bulkCategoryId,setBulkCategoryId]=useState('');const allCategories=useMemo(()=>[...systemCategories,...userCategories],[systemCategories,userCategories]);
const load=async(pageOverride?:number,sizeOverride?:string,filtersOverride?:typeof initialFilters)=>{if(!userId)return;const res=await getTransactions(userId,{...(filtersOverride??filters),page:String(pageOverride??page),size:sizeOverride??size});setRows(res.items);setTotalPages(res.totalPages)};
useEffect(()=>{if(!userId)return;getSystemCategories().then(setSystemCategories);getUserCategories(userId).then(setUserCategories);},[userId]);useEffect(()=>{if(!userId)return;load().catch(e=>setError((e as Error).message));},[userId,page,size]);
return <AppShell><PageHeader title='Transactions' description='Filter, categorize, and manage imported transactions.'/><UserSelector onChange={(id)=>{setUserId(id);setPage(0);}}/>
<SectionCard title='Filters'><div className='grid'><FormField label='From'><input type='date' value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></FormField><FormField label='To'><input type='date' value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></FormField><FormField label='Merchant'><input value={filters.merchant} onChange={e=>setFilters({...filters,merchant:e.target.value})}/></FormField></div><div className='row'><button onClick={async()=>{setPage(0);await load(0,size);}}>Apply filters</button><button className='secondary' onClick={async()=>{setFilters(initialFilters);setPage(0);await load(0,size,initialFilters);}}>Clear filters</button><select value={size} onChange={async e=>{const n=e.target.value;setSize(n);setPage(0);await load(0,n);}}><option>25</option><option>50</option><option>100</option></select><button onClick={()=>setPage(Math.max(0,page-1))} disabled={page===0}>Previous</button><button onClick={()=>setPage(page+1<totalPages?page+1:page)} disabled={page+1>=totalPages}>Next</button></div></SectionCard>
<SectionCard title='Bulk category update'><div className='row'><select value={bulkCategoryId} onChange={e=>setBulkCategoryId(e.target.value)}><option value=''>Uncategorized</option>{allCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={!selectedIds.length} onClick={async()=>{await bulkUpdateTransactionCategory(userId,selectedIds,bulkCategoryId||null);setSelectedIds([]);await load();}}>Apply</button><span className='badge'>{selectedIds.length} selected</span></div></SectionCard>
<ErrorMessage message={error}/>{rows.length===0?<EmptyState title='No transactions found' description='Try changing filters or upload a CSV first.'/>:<table><thead><tr><th></th><th>Date</th><th>Direction</th><th>Amount</th><th>Type</th><th>Source</th><th>Merchant</th><th>Category</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><input type='checkbox' checked={selectedIds.includes(r.id)} onChange={()=>setSelectedIds(p=>p.includes(r.id)?p.filter(x=>x!==r.id):[...p,r.id])}/></td><td>{r.transactionDate}</td><td>{r.direction}</td><td>{formatCurrency(r.amount)}</td><td>{r.transactionType}</td><td>{r.source}</td><td>{r.merchant}</td><td><StatusBadge status={allCategories.find(c=>c.id===r.categoryId)?.name||'UNCATEGORIZED'}/></td><td><button className='danger' onClick={async()=>{if(window.confirm('Delete transaction?')){await deleteTransaction(r.id);await load();}}}>Delete</button></td></tr>)}</tbody></table>}</AppShell>}
