'use client';
import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/AppShell';
import EmptyState from '../../components/EmptyState';
import ErrorMessage from '../../components/ErrorMessage';
import FormField from '../../components/FormField';
import UserSelector from '../../components/UserSelector';
import { formatCurrency } from '../../lib/format';
import { Category, getSystemCategories, getTransactions, getUserCategories, Transaction, updateTransactionCategory } from '../../lib/api';
const initialFilters = { from:'',to:'',merchant:'',transactionType:'',direction:'',minAmount:'',maxAmount:'' };
export default function TransactionsPage(){const [userId,setUserId]=useState(''); const [rows,setRows]=useState<Transaction[]>([]); const [page,setPage]=useState(0); const [size,setSize]=useState('50'); const [totalPages,setTotalPages]=useState(0); const [error,setError]=useState(''); const [filters,setFilters]=useState(initialFilters); const [systemCategories,setSystemCategories]=useState<Category[]>([]); const [userCategories,setUserCategories]=useState<Category[]>([]);
const allCategories=useMemo(()=>[...systemCategories,...userCategories],[systemCategories,userCategories]);
const load=async()=>{if(!userId)return; try{setError(''); const res=await getTransactions(userId,{...filters,page:String(page),size}); setRows(res.items); setTotalPages(res.totalPages);}catch(e){setError((e as Error).message);}};
useEffect(()=>{if(!userId)return; getSystemCategories().then(setSystemCategories).catch(e=>setError((e as Error).message)); getUserCategories(userId).then(setUserCategories).catch(e=>setError((e as Error).message));},[userId]);
const onCategoryChange=async(transactionId:string,categoryId:string)=>{try{const updated=await updateTransactionCategory(transactionId,categoryId||null); setRows(prev=>prev.map(r=>r.id===transactionId?updated:r));}catch(e){setError((e as Error).message);}};
const categoryName=(id:string|null)=>allCategories.find(c=>c.id===id)?.name||'Uncategorized';
return <AppShell><h2>Transactions</h2><UserSelector onChange={setUserId}/><div className='panel'><div className='grid'><FormField label='From'><input type='date' value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></FormField><FormField label='To'><input type='date' value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></FormField><FormField label='Merchant'><input value={filters.merchant} onChange={e=>setFilters({...filters,merchant:e.target.value})}/></FormField><FormField label='Transaction type'><select value={filters.transactionType} onChange={e=>setFilters({...filters,transactionType:e.target.value})}><option value=''>All</option><option value='EXPENSE'>EXPENSE</option><option value='INCOME'>INCOME</option><option value='INVESTMENT'>INVESTMENT</option><option value='LIABILITY_PAYMENT'>LIABILITY_PAYMENT</option></select></FormField><FormField label='Direction'><select value={filters.direction} onChange={e=>setFilters({...filters,direction:e.target.value})}><option value=''>All</option><option value='DEBIT'>DEBIT</option><option value='CREDIT'>CREDIT</option></select></FormField><FormField label='Min amount'><input value={filters.minAmount} onChange={e=>setFilters({...filters,minAmount:e.target.value})}/></FormField><FormField label='Max amount'><input value={filters.maxAmount} onChange={e=>setFilters({...filters,maxAmount:e.target.value})}/></FormField></div><div className='row'><button onClick={load}>Apply filters</button><select value={size} onChange={e=>setSize(e.target.value)}><option>25</option><option>50</option><option>100</option></select><button onClick={()=>{if(page>0){setPage(page-1); setTimeout(load,0);}}}>Previous</button><button onClick={()=>{if(page+1<totalPages){setPage(page+1); setTimeout(load,0);}}}>Next</button><button type='button' className='secondary' onClick={()=>setFilters(initialFilters)}>Clear filters</button></div></div><ErrorMessage message={error} />{rows.length===0?<EmptyState title='No transactions found' description='Try changing filters or upload a CSV first.' />:<table><thead><tr><th>date</th><th>direction</th><th>amount</th><th>type</th><th>merchant</th><th>category</th><th>rawDescription</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.transactionDate}</td><td>{r.direction}</td><td>{formatCurrency(r.amount)}</td><td>{r.transactionType}</td><td>{r.merchant}</td><td><select value={r.categoryId??''} onChange={(e)=>onCategoryChange(r.id,e.target.value)}><option value=''>Uncategorized</option>{systemCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}{userCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div>{categoryName(r.categoryId)}</div></td><td>{r.rawDescription}</td></tr>)}</tbody></table>}</AppShell>}
