'use client';
import { useCallback, useEffect, useState } from 'react';
import AppShell from './AppShell';
import UserSelector from './UserSelector';
import { formatCurrency } from '../lib/format';
import { Account, Category, CreateRecurringTransactionRequest, createRecurringTransaction, deactivateRecurringTransaction, getMonthlyPlanningSummary, getRecurringTransactions, getSystemCategories, getUserAccounts, getUserCategories, MonthlyPlanningSummary, RecurringTransaction } from '../lib/api';

type FormState = { name: string; amount: string; direction: string; transactionType: string; frequency: string; dayOfMonth: string; startDate: string; endDate: string; accountId: string; categoryId: string; notes: string; active: boolean };
const initialForm = (): FormState => ({ name: '', amount: '', direction: 'DEBIT', transactionType: 'EXPENSE', frequency: 'MONTHLY', dayOfMonth: '', startDate: new Date().toISOString().slice(0, 10), endDate: '', accountId: '', categoryId: '', notes: '', active: true });

export default function PlanningPage() { const [userId, setUserId] = useState(''); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [summary, setSummary] = useState<MonthlyPlanningSummary | null>(null); const [recurring, setRecurring] = useState<RecurringTransaction[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [form, setForm] = useState<FormState>(initialForm()); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!userId) return; setError(''); try { const [planning, recurringRows, userAccounts, systemCategories, userCategories] = await Promise.all([getMonthlyPlanningSummary(userId, month), getRecurringTransactions(userId), getUserAccounts(userId), getSystemCategories(), getUserCategories(userId)]); setSummary(planning); setRecurring(recurringRows); setAccounts(userAccounts); setCategories([...systemCategories, ...userCategories]); } catch (e) { setError((e as Error).message); } }, [month, userId]);
  useEffect(() => { load(); }, [load]);
  const submit = async () => { if (!userId) return; const payload: CreateRecurringTransactionRequest = { name: form.name.trim(), amount: Number(form.amount), direction: form.direction, transactionType: form.transactionType, frequency: form.frequency, startDate: form.startDate, active: form.active }; if (form.dayOfMonth.trim()) payload.dayOfMonth = Number(form.dayOfMonth); if (form.endDate.trim()) payload.endDate = form.endDate; if (form.accountId.trim()) payload.accountId = form.accountId; if (form.categoryId.trim()) payload.categoryId = form.categoryId; if (form.notes.trim()) payload.notes = form.notes.trim(); await createRecurringTransaction(userId, payload); setForm(initialForm()); await load(); };
  const metrics:[string,keyof MonthlyPlanningSummary,keyof MonthlyPlanningSummary,keyof MonthlyPlanningSummary][]=[['Income','plannedIncome','actualIncome','incomeVariance'],['Expenses','plannedExpenses','actualExpenses','expensesVariance'],['Investments','plannedInvestments','actualInvestments','investmentsVariance'],['Liabilities','plannedLiabilityPayments','actualLiabilityPayments','liabilityPaymentsVariance'],['Net Cash Flow','plannedNetCashFlow','actualNetCashFlow','netCashFlowVariance']];
  return <AppShell><section className='hero-panel smooth-card'><h1>Plan your month</h1><p className='subtle-text'>Compare expected income, SIPs, EMIs, and expenses with reality.</p><div className='row'><input type='month' value={month} onChange={(e) => setMonth(e.target.value)} /><button onClick={load}>Load summary</button></div></section><UserSelector onChange={setUserId} />{error && <p>{error}</p>}
  {summary && <section className='smooth-card'><div className='transaction-feed'>{metrics.map(([name,p,a,v])=>{const variance=Number(summary[v]||0);return <div key={name} className='transaction-row'><div><b>{name}</b></div><div>{formatCurrency(summary[p] as number)}</div><div>{formatCurrency(summary[a] as number)}</div><div className={`status-chip ${variance<0?'amount-negative':'amount-positive'}`}>{formatCurrency(variance)}</div></div>})}</div></section>}
  <section className='smooth-card'><h3>Create recurring form</h3><div className='grid'><input placeholder='Name' value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder='Amount' type='number' value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option>CREDIT</option><option>DEBIT</option></select><select value={form.transactionType} onChange={(e) => setForm({ ...form, transactionType: e.target.value })}>{['INCOME', 'EXPENSE', 'INVESTMENT', 'LIABILITY_PAYMENT', 'TRANSFER', 'REFUND', 'ADJUSTMENT'].map((v) => <option key={v}>{v}</option>)}</select><select value={form.frequency} onChange={(e) => setForm({ ...form, frequency: e.target.value })}><option>MONTHLY</option><option>QUARTERLY</option><option>YEARLY</option></select><input placeholder='Day' type='number' value={form.dayOfMonth} onChange={(e) => setForm({ ...form, dayOfMonth: e.target.value })} /><input type='date' value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /><input type='date' value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /><select value={form.accountId} onChange={(e) => setForm({ ...form, accountId: e.target.value })}><option value=''>No account</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value=''>No category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea placeholder='Notes' value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div><button onClick={submit}>Create recurring transaction</button></section>
  <section className='smooth-card'><h3>Recurring templates</h3><div className='transaction-feed'>{recurring.map((x)=><div key={x.id} className='transaction-row'><div><b>{x.name}</b></div><div>{formatCurrency(x.amount)}</div><div>{x.frequency} · {x.dayOfMonth ?? '-'}</div><div>{x.transactionType}</div><div>{x.startDate}</div><div>{x.active?'Active':'Inactive'}</div><div>{x.active ? <button className='danger-button' onClick={async () => { await deactivateRecurringTransaction(x.id); await load(); }}>Deactivate</button> : '-'}</div></div>)}</div></section></AppShell>; }
