'use client';
import { useEffect, useState } from 'react';
import UserSelector from '../../components/UserSelector';
import { Account, getUserAccounts, ImportSummary, uploadTransactionsCsv } from '../../lib/api';

export default function UploadPage(){const [userId,setUserId]=useState(''); const [accounts,setAccounts]=useState<Account[]>([]); const [accountId,setAccountId]=useState(''); const [source,setSource]=useState('MANUAL'); const [file,setFile]=useState<File|null>(null); const [result,setResult]=useState<ImportSummary|null>(null); const [error,setError]=useState('');
useEffect(()=>{if(!userId)return; getUserAccounts(userId).then(setAccounts).catch(e=>setError((e as Error).message));},[userId]);
const upload=async()=>{if(!userId||!accountId||!file)return; try{setError(''); setResult(await uploadTransactionsCsv(userId,accountId,file,source));}catch(e){setError((e as Error).message);}};
return <main className='container'><h2>Upload CSV</h2><UserSelector onChange={setUserId}/><div className='panel'><select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value=''>Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}>{['MANUAL','BANK_STATEMENT','CREDIT_CARD_STATEMENT'].map(s=><option key={s}>{s}</option>)}</select><input type='file' accept='.csv' onChange={e=>setFile(e.target.files?.[0]??null)}/><button onClick={upload}>Upload</button></div><pre>transactionDate,direction,amount,rawDescription,merchant,transactionType,categoryName,notes
2026-05-01,DEBIT,1250.00,Swiggy order,Swiggy,EXPENSE,Food,Dinner</pre>{error&&<p className='warn'>{error}</p>}{result&&<div className='panel'><p>status: {result.status}</p><p>totalRows: {result.totalRows}</p><p>createdCount: {result.createdCount}</p><p>skippedDuplicateCount: {result.skippedDuplicateCount}</p><p>failedCount: {result.failedCount}</p><table><thead><tr><th>row</th><th>message</th></tr></thead><tbody>{result.errors.map((e,i)=><tr key={i}><td>{e.rowNumber}</td><td>{e.message}</td></tr>)}</tbody></table></div>}</main>;}
