spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fathom}
    username: ${SPRING_DATASOURCE_USERNAME:fathom}
    password: ${SPRING_DATASOURCE_PASSWORD:fathom_dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080
