spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fathom
    username: fathom
    password: fathom_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080
