'use client';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';import UserSelector from '../../components/UserSelector';import ErrorMessage from '../../components/ErrorMessage';import { createBudget, deactivateBudget, getBudgetSummary, getBudgets, getSystemCategories, getUserCategories } from '../../lib/api';import { formatCurrency, formatPercent } from '../../lib/format';
export default function BudgetsPage(){const [userId,setUserId]=useState('');const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const [budgets,setBudgets]=useState<any[]>([]);const [summary,setSummary]=useState<any[]>([]);const [cats,setCats]=useState<any[]>([]);const [error,setError]=useState('');const [form,setForm]=useState({name:'',month:new Date().toISOString().slice(0,7),amount:'',categoryId:'',notes:'',active:true});
useEffect(()=>{if(!userId)return; Promise.all([getSystemCategories(),getUserCategories(userId)]).then(([s,u])=>setCats([...s,...u])).catch(e=>setError(e.message));},[userId]);
const load=()=>{if(!userId)return; Promise.all([getBudgets(userId,month),getBudgetSummary(userId,month)]).then(([b,s])=>{setBudgets(b);setSummary(s);}).catch(e=>setError(e.message));};
return <AppShell><h2>Budgets</h2><UserSelector onChange={setUserId}/><ErrorMessage message={error}/><input type='month' value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={load}>Load budgets</button><div className='panel'><h3>Create budget</h3><input placeholder='Name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type='month' value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/><input placeholder='Amount' value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value=''>General</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={!userId||!form.name||!form.month||!form.amount} onClick={async()=>{await createBudget(userId,{...form,categoryId:form.categoryId||null,amount:Number(form.amount)} as any);load();}}>Create</button></div>
<h3>Budget Summary</h3><table><thead><tr><th>Name</th><th>Category</th><th>Budget</th><th>Actual</th><th>Remaining</th><th>Usage</th><th>Status</th></tr></thead><tbody>{summary.map(s=><tr key={s.budgetId}><td>{s.name}</td><td>{s.categoryName||'General'}</td><td>{formatCurrency(s.budgetAmount)}</td><td>{formatCurrency(s.actualAmount)}</td><td>{formatCurrency(s.remainingAmount)}</td><td>{formatPercent(s.usagePercent)}</td><td>{s.status}</td></tr>)}</tbody></table>
<h3>Budgets</h3><table><thead><tr><th>Name</th><th>Month</th><th>Category</th><th>Amount</th><th>Active</th><th/></tr></thead><tbody>{budgets.map(b=><tr key={b.id}><td>{b.name}</td><td>{b.month}</td><td>{cats.find(c=>c.id===b.categoryId)?.name||'General'}</td><td>{formatCurrency(b.amount)}</td><td>{String(b.active)}</td><td><button onClick={async()=>{await deactivateBudget(b.id);load();}}>Deactivate</button></td></tr>)}</tbody></table></AppShell>}
