'use client';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import UserSelector from '../../components/UserSelector';
import ErrorMessage from '../../components/ErrorMessage';
import { createBudget, deactivateBudget, getBudgetSummary, getBudgets, getSystemCategories, getUserCategories } from '../../lib/api';
import { formatCurrency, formatPercent } from '../../lib/format';

export default function BudgetsPage(){const [userId,setUserId]=useState('');const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const [budgets,setBudgets]=useState<any[]>([]);const [summary,setSummary]=useState<any[]>([]);const [cats,setCats]=useState<any[]>([]);const [error,setError]=useState('');const [form,setForm]=useState({name:'',month:new Date().toISOString().slice(0,7),amount:'',categoryId:'',notes:'',active:true});
useEffect(()=>{if(!userId)return; Promise.all([getSystemCategories(),getUserCategories(userId)]).then(([s,u])=>setCats([...s,...u])).catch(e=>setError(e.message));},[userId]);
const load=()=>{if(!userId)return; Promise.all([getBudgets(userId,month),getBudgetSummary(userId,month)]).then(([b,s])=>{setBudgets(b);setSummary(s);}).catch(e=>setError(e.message));};
return <AppShell><section className='hero-panel smooth-card'><h1>Budget control</h1><p className='subtle-text'>Set monthly limits and track overspending.</p><div className='row'><input type='month' value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={load}>Load</button></div></section><UserSelector onChange={setUserId}/><ErrorMessage message={error}/>
<section className='smooth-card'><h3>Create budget</h3><div className='grid'><input placeholder='Name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type='month' value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/><input placeholder='Amount' value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value=''>General</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className='row'><button disabled={!userId||!form.name||!form.month||!form.amount} onClick={async()=>{await createBudget(userId,{...form,categoryId:form.categoryId||null,amount:Number(form.amount)} as any);load();}}>Create</button></div></section>
<section className='smooth-card'><h3>Top summary</h3><div className='transaction-feed'>{summary.map(s=><div key={s.budgetId} className='transaction-row'><div><b>{s.name}</b></div><div>{s.categoryName||'General'}</div><div>{formatCurrency(s.budgetAmount)}</div><div>{formatCurrency(s.actualAmount)}</div><div>{formatCurrency(s.remainingAmount)}</div><div>{formatPercent(s.usagePercent)}</div><div className='status-chip'>{s.status}</div></div>)}</div></section>
<section className='smooth-card'><h3>Budget cards</h3><div className='transaction-feed'>{budgets.map(b=><div key={b.id} className='transaction-row'><div><b>{b.name}</b></div><div>{b.month}</div><div>{cats.find(c=>c.id===b.categoryId)?.name||'General'}</div><div>{formatCurrency(b.amount)}</div><div className='status-chip'>{String(b.active?'ACTIVE':'INACTIVE')}</div><div><button className='danger-button' onClick={async()=>{await deactivateBudget(b.id);load();}}>Deactivate</button></div></div>)}</div></section></AppShell>}
