'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import ErrorMessage from '../../components/ErrorMessage';
import FormField from '../../components/FormField';
import { compactId } from '../../lib/format';
import { Account, createAccount, createUser, CreateAccountRequest, CreateUserRequest, getUsers, User } from '../../lib/api';

const accountTypes = ['BANK_ACCOUNT', 'CREDIT_CARD', 'BROKERAGE', 'CASH', 'LOAN', 'MANUAL'];
export default function SetupPage(){const [userForm,setUserForm]=useState<CreateUserRequest>({name:'',email:'',status:'ACTIVE'}); const [accountForm,setAccountForm]=useState<CreateAccountRequest>({name:'',institutionName:'',accountType:'BANK_ACCOUNT',currency:'INR',maskedIdentifier:''}); const [userId,setUserId]=useState(''); const [createdUser,setCreatedUser]=useState<User|null>(null); const [createdAccount,setCreatedAccount]=useState<Account|null>(null); const [users,setUsers]=useState<User[]>([]); const [loadingUser,setLoadingUser]=useState(false); const [loadingAccount,setLoadingAccount]=useState(false); const [errorUser,setErrorUser]=useState(''); const [errorAccount,setErrorAccount]=useState('');
useEffect(()=>{setUserId(localStorage.getItem('fathom.userId') ?? '');},[]); useEffect(()=>{getUsers().then(setUsers).catch(()=>setUsers([]));},[]);
const onCreateUser=async(e:FormEvent)=>{e.preventDefault(); setLoadingUser(true); setErrorUser(''); try{const created=await createUser(userForm); setCreatedUser(created); setUserId(created.id); setUsers((p)=>[created,...p]); localStorage.setItem('fathom.userId',created.id);}catch(err){setErrorUser((err as Error).message);}finally{setLoadingUser(false);}};
const onCreateAccount=async(e:FormEvent)=>{e.preventDefault(); if(!userId) return; setLoadingAccount(true); setErrorAccount(''); try{const payload=Object.fromEntries(Object.entries(accountForm).filter(([,v])=>v!=='')) as CreateAccountRequest; const created=await createAccount(userId,payload); setCreatedAccount(created);}catch(err){setErrorAccount((err as Error).message);}finally{setLoadingAccount(false);}};
return <AppShell><h2>Setup</h2><section className='panel'><h3>Step 1: Create User</h3><form onSubmit={onCreateUser}><FormField label='Name'><input value={userForm.name} onChange={(e)=>setUserForm({...userForm,name:e.target.value})} required /></FormField><FormField label='Email'><input type='email' value={userForm.email} onChange={(e)=>setUserForm({...userForm,email:e.target.value})} required /></FormField><FormField label='Status'><select value={userForm.status} onChange={(e)=>setUserForm({...userForm,status:e.target.value})}><option value='ACTIVE'>ACTIVE</option><option value='INACTIVE'>INACTIVE</option></select></FormField><button type='submit' disabled={loadingUser}>{loadingUser?'Creating user...':'Create User'}</button></form><ErrorMessage message={errorUser} />{createdUser && <p>User saved: <strong>{compactId(createdUser.id)}</strong></p>}{users.length>0&&<p className='muted'>Existing users found: {users.length}</p>}</section><section className='panel'><h3>Step 2: Create Account</h3><form onSubmit={onCreateAccount}><FormField label='Account name'><input value={accountForm.name} onChange={(e)=>setAccountForm({...accountForm,name:e.target.value})} disabled={!userId} required/></FormField><FormField label='Institution name'><input value={accountForm.institutionName ?? ''} onChange={(e)=>setAccountForm({...accountForm,institutionName:e.target.value})} disabled={!userId}/></FormField><FormField label='Account type'><select value={accountForm.accountType} onChange={(e)=>setAccountForm({...accountForm,accountType:e.target.value})} disabled={!userId}>{accountTypes.map((t)=><option key={t} value={t}>{t}</option>)}</select></FormField><button type='submit' disabled={!userId || loadingAccount}>{loadingAccount?'Creating account...':'Create Account'}</button></form><ErrorMessage message={errorAccount} />{createdAccount && <p>Account saved: <strong>{createdAccount.name}</strong> ({createdAccount.accountType})</p>}</section><section className='panel'><h3>Step 3: Continue</h3><div className='row'><Link href='/upload'>Go to Upload</Link><Link href='/dashboard'>Go to Dashboard</Link></div></section></AppShell>;}
