'use client';
import Link from 'next/link';
import { useCallback, useState } from 'react';
import AppShell from '../../components/AppShell';
import EmptyState from '../../components/EmptyState';
import ErrorMessage from '../../components/ErrorMessage';
import LoadingMessage from '../../components/LoadingMessage';
import MetricGrid from '../../components/MetricGrid';
import PageHeader from '../../components/PageHeader';
import ProgressBar from '../../components/ProgressBar';
import SectionCard from '../../components/SectionCard';
import StatCard from '../../components/StatCard';
import StatusBadge from '../../components/StatusBadge';
import UserSelector from '../../components/UserSelector';
import { formatCurrency, formatPercent } from '../../lib/format';
import { getBudgetSummary, getCategoryBreakdown, getMonthlySummary, getNetWorth } from '../../lib/api';
function getMonthDateRange(month: string) { const [y, m] = month.split('-'); const d = new Date(Number(y), Number(m), 0).getDate(); return { from: `${month}-01`, to: `${month}-${String(d).padStart(2, '0')}` }; }
export default function DashboardPage(){const [userId,setUserId]=useState('');const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const [data,setData]=useState<any>(null);const [breakdown,setBreakdown]=useState<any[]>([]);const [budgetSummary,setBudgetSummary]=useState<any[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
const load=useCallback(async()=>{if(!userId)return;const range=getMonthDateRange(month);setLoading(true);setError('');try{const [summary,cat,net,b]=await Promise.all([getMonthlySummary(userId,month),getCategoryBreakdown(userId,range.from,range.to,'EXPENSE'),getNetWorth(userId),getBudgetSummary(userId,month)]);setData({...summary,...net});setBreakdown(cat);setBudgetSummary(b)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[month,userId]);
return <AppShell><PageHeader title='Your money at a glance' description='Track spending, savings, and net worth with a premium monthly snapshot.' action={<div className='row'><input type='month' value={month} onChange={e=>setMonth(e.target.value)}/><button onClick={load}>Refresh</button></div>} /><UserSelector onChange={setUserId}/>{loading&&<LoadingMessage message='Loading dashboard...'/>}<ErrorMessage message={error}/>{data&&<MetricGrid>{[{k:'income',l:'Income',i:'💰',t:'positive'},{k:'expenses',l:'Expenses',i:'💸',t:'negative'},{k:'investments',l:'Investments',i:'📈',t:'positive'},{k:'liabilityPayments',l:'Liability Payments',i:'🏦',t:'negative'},{k:'netCashFlow',l:'Net Cash Flow',i:'🧮',t:data.netCashFlow>=0?'positive':'negative'},{k:'savingsRate',l:'Savings Rate',i:'🎯',f:formatPercent,t:'positive'},{k:'netWorth',l:'Net Worth',i:'🪙',t:data.netWorth>=0?'positive':'negative'}].map((m:any)=><StatCard key={m.k} label={m.l} icon={m.i} tone={m.t} value={(m.f||formatCurrency)(data[m.k]||0)} />)}</MetricGrid>}<SectionCard title='Category breakdown'>{breakdown.length===0?<EmptyState title='No category rows yet' description='No transactions found for this month.' action={<Link href='/upload'>Upload CSV</Link>} />:<table><thead><tr><th>Category</th><th>Amount</th><th>Share</th></tr></thead><tbody>{breakdown.map((r,i)=>{const p=Math.round((r.percentage||0)*100);return <tr key={i}><td>{r.categoryName}</td><td>{formatCurrency(r.amount)}</td><td><div className='row'><div style={{minWidth:45}}>{p}%</div><div style={{flex:1}}><ProgressBar value={p}/></div></div></td></tr>})}</tbody></table>}</SectionCard><SectionCard title='Budget snapshot'><p><Link href='/budgets'>Go to Budgets →</Link></p>{budgetSummary.length===0?<EmptyState title='No budgets for this month'/>:<table><thead><tr><th>Name</th><th>Budget</th><th>Actual</th><th>Usage</th><th>Status</th></tr></thead><tbody>{budgetSummary.map((b:any)=><tr key={b.budgetId}><td>{b.name}</td><td>{formatCurrency(b.budgetAmount)}</td><td>{formatCurrency(b.actualAmount)}</td><td><ProgressBar value={b.usagePercent*100}/></td><td><StatusBadge status={b.status}/></td></tr>)}</tbody></table>}</SectionCard><SectionCard title='Quick actions'><div className='row'><Link href='/upload'><button>Upload CSV</button></Link><Link href='/budgets'><button className='secondary'>Add Budget</button></Link><Link href='/transactions'><button className='secondary'>Open Transactions</button></Link><Link href='/planning'><button className='secondary'>Open Planning</button></Link></div></SectionCard></AppShell>}
